# Site settings
name: Aldi Aulia Perdana
description: "Belajar Buat Github"
url: https://perdanaaldi.github.io


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  perdanaaldi.github.io
facebook_username: Aldi Aulia Perdana
google_plus_username: aldiaperdanaa2
linkedin_username: aldiaulia
instagram_username:  perdanaaldi
email: aldiaperdanaa2@gmail.com


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "img/profil.jpg"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
